import { ContextProvider } from '@/context';
import { Inter } from 'next/font/google';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ContextProvider>
        <body className={inter.className}>
          {children}
          <div id="modal-root" />
          <ToastContainer autoClose={1000}
hideProgressBar={true} />
        </body>
      </ContextProvider>
    </html>
  );
}
